apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: russ-prometheus
    access: proxy
    url: http://russ-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
